# Generated by Django 4.2.16 on 2025-01-29 14:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Patient Home Address'),
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of Birth'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='family_history',
            field=models.CharField(blank=True, null=True, verbose_name='Family Illness'),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, verbose_name='Sex'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='guardian',
            field=models.BooleanField(default=False, verbose_name='if parent'),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record', to='patients.patient'),
        ),
        migrations.CreateModel(
            name='PatientDependant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('age', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Sex')),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='patients.patient')),
            ],
            options={
                'verbose_name': 'dependant',
                'verbose_name_plural': 'dependants',
            },
        ),
    ]
