# Generated by Django 4.2.16 on 2025-01-30 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_address_patient_age_patient_family_history_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientrecord',
            options={},
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.CharField(blank=True, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='dependant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependant', to='patients.patientdependant'),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='reason',
            field=models.TextField(verbose_name='Reason for visit'),
        ),
        migrations.AddConstraint(
            model_name='patientrecord',
            constraint=models.CheckConstraint(check=models.Q(('patient__isnull', False), ('dependant__isnull', False), _connector='OR'), name='record_must_have_patient_or_dependant'),
        ),
        migrations.AddConstraint(
            model_name='patientrecord',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('patient__isnull', False), _negated=True), models.Q(('dependant__isnull', False), _negated=True), _connector='OR'), name='record_cannot_have_both_patient_and_dependant'),
        ),
    ]
