# Generated by Django 4.2.16 on 2025-02-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patientrecord_options_patient_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='character',
            field=models.TextField(blank=True, null=True, verbose_name='Character of Pain/Symptoms'),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='complaint',
            field=models.TextField(blank=True, null=True, verbose_name='Chief Complaint'),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='factors',
            field=models.TextField(blank=True, null=True, verbose_name='Aggreviating factors'),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='location',
            field=models.TextField(null=True, verbose_name='Location of Symptoms'),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='onset',
            field=models.TextField(blank=True, null=True, verbose_name='Onset of Symptoms'),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='severity',
            field=models.TextField(blank=True, null=True, verbose_name='Severity of the symptoms'),
        ),
    ]
