# Generated by Django 4.2.16 on 2025-02-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patientrecord_character_patientrecord_complaint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='appointment',
            field=models.TextField(blank=True, null=True, verbose_name='Reason for booking an appointment'),
        ),
    ]
