# Generated by Django 4.2.16 on 2025-02-10 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_diseasemanagementrecord_patientrecord_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaternityCareRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edd', models.DateField(verbose_name='Estimated Delivery Date')),
                ('gravidity', models.IntegerField(blank=True, null=True, verbose_name='Number of total pregnancie')),
                ('parity', models.IntegerField(blank=True, null=True, verbose_name='Number of previous deliveries')),
                ('lmp', models.DateField(verbose_name='Last Menstral Period')),
                ('ppc', models.TextField(blank=True, null=True, verbose_name='Previous Pregnancy Complications')),
                ('pbc', models.TextField(blank=True, null=True, verbose_name='Previous Birth Complications')),
                ('place_of_birth', models.CharField(blank=True, null=True, verbose_name='Preferred Place of Birth')),
                ('pain_management', models.CharField(blank=True, null=True, verbose_name='Preferred Pain Management')),
            ],
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='maternity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maternity', to='patients.maternitycarerecord'),
        ),
    ]
