# Generated by Django 4.2.16 on 2025-02-11 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_maternitycarerecord_patientrecord_maternity'),
    ]

    operations = [
        migrations.CreateModel(
            name='RehabilitationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=50, verbose_name='Diagnosis')),
                ('injury_date', models.DateField(verbose_name='Onset')),
                ('injury_type', models.CharField(max_length=100, verbose_name='Condition of INJURY')),
            ],
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='injuries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to='patients.rehabilitationrecord'),
        ),
    ]
