# Generated by Django 4.2.16 on 2025-02-14 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_rehabilitationrecord_patientrecord_injuries'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='temp')),
                ('pulse', models.FloatField(blank=True, null=True, verbose_name='Pulse')),
                ('blood_pressure', models.CharField(blank=True, null=True, verbose_name='bp')),
                ('respiratory_rate', models.FloatField(blank=True, null=True, verbose_name='RR')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Weight')),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Height')),
                ('neurological', models.TextField(blank=True, null=True, verbose_name='NA')),
                ('respiratory', models.TextField(blank=True, null=True, verbose_name='RA')),
                ('cardiovascular', models.TextField(blank=True, null=True, verbose_name='CA')),
                ('gastrointestinal', models.TextField(blank=True, null=True, verbose_name='GA')),
                ('musculoskeleton', models.TextField(blank=True, null=True, verbose_name='MA')),
                ('skin', models.TextField(blank=True, null=True, verbose_name='SA')),
                ('pyschological', models.TextField(blank=True, null=True, verbose_name='PA')),
                ('pain', models.TextField(blank=True, null=True, verbose_name='Pain Assessment')),
                ('fall_risk', models.TextField(blank=True, null=True, verbose_name='FR')),
            ],
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='vitals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vital', to='patients.vitalsmodel'),
        ),
    ]
