# Generated by Django 4.2.16 on 2025-02-14 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_vitalsmodel_patientrecord_vitals'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentPlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.TextField(verbose_name='Treatment Plan')),
                ('diagnosis', models.TextField(verbose_name='Diagnosis')),
                ('medication', models.JSONField(blank=True, null=True, verbose_name='Prescription')),
            ],
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='treatment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatmentPlan', to='patients.treatmentplanmodel'),
        ),
    ]
