# Generated by Django 4.2.16 on 2025-01-27 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'verbose_name': 'medicine', 'verbose_name_plural': 'Medicine'},
        ),
        migrations.AlterUniqueTogether(
            name='medicine',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='medicine',
            name='batch_number',
            field=models.CharField(default='8797jk', unique=True, verbose_name='Batch Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Expiry Date'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MedicineHistory',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='category',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='dosage_form',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='dosage_quantity',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='name',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='updated_at',
        ),
    ]
