# Generated by Django 4.2.16 on 2025-01-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_medicine_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='manufacturer',
            field=models.CharField(default='jkl', max_length=50, verbose_name='Manufacturer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='supplier',
            field=models.CharField(default='spil', max_length=50, verbose_name='Supplier'),
            preserve_default=False,
        ),
    ]
