# Generated by Django 4.2.16 on 2025-01-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_medicine_manufacturer_medicine_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='cost',
            field=models.FloatField(default=0.0, verbose_name='Unit Cost'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='name',
            field=models.CharField(default='qwerty', max_length=50, verbose_name='Medicine Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Price'),
        ),
    ]
