# Generated by Django 4.2.16 on 2025-01-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0005_medicine_cost_medicine_name_medicine_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='administration',
            field=models.CharField(default='mouth', verbose_name='Intake Route'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='strength',
            field=models.PositiveBigIntegerField(default=1000, verbose_name='Dose Strength'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='type',
            field=models.JSONField(default='Antibiotics', verbose_name='Medicine class'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
