# Generated by Django 4.2.16 on 2025-01-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='start time')),
                ('end', models.DateTimeField(verbose_name='end time')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('attended', models.BooleanField(default=False, verbose_name='attended')),
                ('reason', models.CharField(blank=True, verbose_name='description')),
                ('patientId', models.CharField(blank=True, verbose_name='patient detail')),
                ('missed', models.BooleanField(default=False, verbose_name='missed')),
                ('missed_reason', models.CharField(blank=True, verbose_name='reason for missed appointment')),
                ('reschedule_reason', models.CharField(blank=True, verbose_name='reason for reschedule')),
            ],
            options={
                'verbose_name': 'appointment',
                'verbose_name_plural': 'appointments',
            },
        ),
    ]
