# Generated by Django 4.2.16 on 2025-01-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointments_scheduled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='email',
            field=models.CharField(default=False, max_length=50, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='follow_up_approach',
            field=models.CharField(blank=True, verbose_name='Follow up method'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='mobile',
            field=models.CharField(default=False, max_length=13, verbose_name='mobile number'),
        ),
    ]
