# Generated by Django 4.2.16 on 2025-01-21 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0003_appointments_email_appointments_follow_up_approach_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='patientId',
        ),
        migrations.AddField(
            model_name='appointments',
            name='first_name',
            field=models.CharField(blank=True, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='last_name',
            field=models.CharField(blank=True, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='appointments',
            name='middle_name',
            field=models.CharField(blank=True, verbose_name='middle name'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='end',
            field=models.DateTimeField(verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='follow_up_approach',
            field=models.CharField(blank=True, verbose_name='Follow up approach'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='missed_reason',
            field=models.CharField(blank=True, verbose_name='missed reason'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='mobile',
            field=models.CharField(default=False, max_length=13, verbose_name='mobile'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='reason',
            field=models.CharField(blank=True, verbose_name='reason'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='reschedule_reason',
            field=models.CharField(blank=True, verbose_name='reschedule reason'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='scheduled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='start',
            field=models.DateTimeField(verbose_name='start'),
        ),
    ]
